# Generated by Django 5.1.3 on 2024-11-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_dayssummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaysSummary',
        ),
        migrations.CreateModel(
            name='DaysSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата Вступления')),
            ],
            options={
                'verbose_name': 'Дни',
                'verbose_name_plural': 'Дни',
                'abstract': False,
            },
        ),
    ]
