# Generated by Django 5.1.3 on 2024-11-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_delete_dayssummary_dayssummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Закупщик',
                'verbose_name_plural': 'Закупщик',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dayssummary',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='link',
            name='buyer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.buyer', verbose_name='Закупщик'),
        ),
    ]
