# Generated by Django 5.1.3 on 2024-11-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_buyer_alter_dayssummary_date_link_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='buyer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.buyer', verbose_name='Закупщик'),
        ),
    ]
