# Generated by Django 5.1.3 on 2025-01-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_daysrangesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetable',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата Вступления'),
        ),
    ]
