# Generated by Django 5.1.3 on 2025-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_basetable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayssummary',
            name='buyers',
            field=models.ManyToManyField(to='bot.buyer', verbose_name='Закупщики'),
        ),
    ]
