# Generated by Django 5.1.3 on 2025-01-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_dayssummary_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayssummary',
            name='buyers',
            field=models.ManyToManyField(blank=True, to='bot.buyer', verbose_name='Закупщики'),
        ),
    ]
