# Generated by Django 5.1.3 on 2025-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_dayssummary_buyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayssummary',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
