# Generated by Django 5.1.3 on 2025-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_dayssummary_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daysrangesummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='daysrangesummary',
            name='buyers',
            field=models.ManyToManyField(blank=True, to='bot.buyer', verbose_name='Закупщики'),
        ),
    ]
