# Generated by Django 5.1.3 on 2025-01-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_linkfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkfilter',
            name='invite_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.link', verbose_name='Ссылка'),
        ),
    ]
