# Generated by Django 5.1.3 on 2025-08-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_linkfilter_invite_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, editable=False, max_length=64, null=True, verbose_name='Имя')),
                ('user_name', models.CharField(blank=True, default=None, editable=False, max_length=32, null=True, verbose_name='Юзернейм')),
                ('last_name', models.CharField(blank=True, default=None, editable=False, max_length=64, null=True, verbose_name='Фамилия')),
                ('registratin_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата Регистрации')),
            ],
            options={
                'verbose_name': 'Админ телеграм',
                'verbose_name_plural': 'Админ телеграм',
                'abstract': False,
            },
        ),
    ]
