# Generated by Django 5.1.3 on 2025-08-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='registratin_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата Добавления'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
